/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vannguyen.Views;

import com.vannguyen.Dao.NewDao;
import com.vannguyen.Model.SoLL;
import com.vannguyen.Services.GiaovienServices;
import com.vannguyen.Services.SoLLServices;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen
 */
public class InputSoLL extends javax.swing.JPanel {

    /**
     * Creates new form InputSoLL
     */
//    String string = txtMaGV.getText().trim();
//    maGV  = string.substring(2);
//    maSo += namHoc + maGV ;
//
//    txtMaSo.setText (maSo);
//
//    String stringA = txtNamHoc.getText().trim();
//    String stringB = txtNamHoc.getText().trim();
//    namHoc  = stringA.substring(2, 4) + stringB.substring(7);
//    maSo += namHoc ;
//
//    txtMaSo.setText (maSo);
    SoLLServices soLLServices;
    DefaultTableModel defaultTableModel;
    GiaovienServices giaovienServices;
    String maSo = "";
    String maGVA = "";
    String maGVB = "";
    String namHocA = "";
    String namHocB = "";

    public InputSoLL() {
        initComponents();
        soLLServices = new SoLLServices();
        giaovienServices = new GiaovienServices();
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table.setModel(defaultTableModel);
        table.setAutoCreateRowSorter(true);
        defaultTableModel.addColumn("Mã sổ");
        defaultTableModel.addColumn("Mã giáo viên");
        defaultTableModel.addColumn("Mã đơn vị");
        defaultTableModel.addColumn("Năm học");
        FillData(soLLServices.getSoLL());
        LoadComboBox();
        loadMaGV();
    }

    private void LoadComboBox() {
        ArrayList<String> list = NewDao.loadNamhocToCombo();
        for (String item : list) {
            comboNamHoc.addItem(item);
        }
    }
    
    private void loadMaGV(){
        ArrayList<String> list = NewDao.loadMaGVtoCombo();
        for (String item : list) {
            comboMaGV.addItem(item);
        }
   }

    private void FillData(List<SoLL> list) {
        defaultTableModel.setRowCount(0);
        for (SoLL soLL : list) {
            defaultTableModel.addRow(new Object[]{
                soLL.getMaSo(),
                soLL.getMaGiaovien(),
                soLL.getMaDonvi(),
                soLL.getNamHoc()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaSo = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnReLoad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnReDo = new javax.swing.JButton();
        comboNamHoc = new javax.swing.JComboBox<>();
        btnAddNamHoc = new javax.swing.JButton();
        comboMaGV = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Sổ lên lớp");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Mã sổ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Mã giáo viên");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Năm học");

        txtMaSo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMaSo.setEnabled(false);

        btnAdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAdd.setText("Thêm mới");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnReLoad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnReLoad.setText("Tải lại giao diện");
        btnReLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReLoadActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        btnCreate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCreate.setText("Tạo mã sổ");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnReDo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnReDo.setText("Nhập lại");
        btnReDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReDoActionPerformed(evt);
            }
        });

        comboNamHoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnAddNamHoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAddNamHoc.setText("Thêm năm học mới");
        btnAddNamHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNamHocActionPerformed(evt);
            }
        });

        comboMaGV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMaSo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCreate))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnReDo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnReLoad))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(comboMaGV, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboNamHoc, javax.swing.GroupLayout.Alignment.LEADING, 0, 108, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAddNamHoc)))))
                        .addGap(0, 480, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNamHoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnReLoad)
                    .addComponent(btnReDo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ShowError(String detail) {
        JOptionPane.showMessageDialog(this, detail, "Đã xảy ra lỗi", JOptionPane.ERROR_MESSAGE);
    }
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:

        maGVB = comboMaGV.getSelectedItem().toString();
        String stringNH = comboNamHoc.getSelectedItem().toString();
        namHocB = stringNH;
        maGVA = maGVB.substring(2);
        namHocA = stringNH.substring(2, 4) + stringNH.substring(7);
        maSo = "S" + namHocA + maGVA;
        txtMaSo.setText(maSo);

    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnReDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReDoActionPerformed
        // TODO add your handling code here:
        maSo = "";
        maGVA = "";
        namHocA = "";
        txtMaSo.setText("");
    }//GEN-LAST:event_btnReDoActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (txtMaSo.getText().trim().isEmpty()) {
            ShowError("Vui lòng tạo mã sổ");
        } else {
            if (soLLServices.DuplicateSoLL(maSo)) {
                ShowError("Mã sổ đã tồn tại");
            } else {
                String maDV = NewDao.getDonviOfGiaovien(maGVB);
                SoLL soLL = new SoLL(maSo, maGVB, maDV, namHocB);
                soLLServices.addSoLL(soLL);
                FillData(soLLServices.getSoLL());
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnReLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReLoadActionPerformed
        // TODO add your handling code here:
        FillData(soLLServices.getSoLL());
        comboNamHoc.removeAllItems();
        LoadComboBox();
        comboMaGV.removeAllItems();
        loadMaGV();
    }//GEN-LAST:event_btnReLoadActionPerformed

    private void btnAddNamHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNamHocActionPerformed
        // TODO add your handling code here:
        new InputNamHoc().setVisible(true);
    }//GEN-LAST:event_btnAddNamHocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddNamHoc;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnReDo;
    private javax.swing.JButton btnReLoad;
    private javax.swing.JComboBox<String> comboMaGV;
    private javax.swing.JComboBox<String> comboNamHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtMaSo;
    // End of variables declaration//GEN-END:variables
}
