/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vannguyen.Views;
import com.vannguyen.Services.LopServices;
import com.vannguyen.Model.Lop;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Nguyen
 */
public class InputLop extends javax.swing.JPanel {

    /**
     * Creates new form InputLop
     */
    LopServices lopServices;
    DefaultTableModel defaultTableModel;
    public InputLop() {
        initComponents();
        lopServices = new LopServices();
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table.setModel(defaultTableModel);
        table.setAutoCreateRowSorter(true);
        defaultTableModel.addColumn("Mã lớp");
        defaultTableModel.addColumn("Tên lớp");
        fillData(lopServices.getLop());
    }
    private void fillData(List<Lop> list) {
        for (Lop lop : list) {
            defaultTableModel.addRow(new Object[]{lop.getMaLop(), lop.getTenLop()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReLoad = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTenLop = new javax.swing.JEditorPane();
        labelTitile = new javax.swing.JLabel();
        labelMaLop = new javax.swing.JLabel();
        labelTenLop = new javax.swing.JLabel();
        txtMaLop = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(800, 700));

        btnReLoad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnReLoad.setText("Tải lại giao diện");
        btnReLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReLoadActionPerformed(evt);
            }
        });

        txtTenLop.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(txtTenLop);

        labelTitile.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelTitile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitile.setText("Nhập thông tin lớp học");

        labelMaLop.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelMaLop.setText("Mã lớp");

        labelTenLop.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelTenLop.setText("Tên lớp");

        txtMaLop.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnAdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        table.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitile, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMaLop, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelTenLop, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnReLoad))
                                    .addComponent(txtMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitile, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMaLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaLop))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTenLop)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnReLoad))
                        .addGap(218, 218, 218))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReLoadActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        fillData(lopServices.getLop());
    }//GEN-LAST:event_btnReLoadActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (txtMaLop.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền mã lớp", "Đã xảy ra lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            String malop = txtMaLop.getText();
            String reg = "^\\w{2}\\d{3}$";
            if (!malop.matches(reg)) {
                JOptionPane.showMessageDialog(this, "Mã lớp không đúng định dạng"
                    + "\nVí dụ: LA123", "Đã xảy ra lỗi", JOptionPane.ERROR_MESSAGE);
            } else {
                if (lopServices.DuplicateLop(malop)) {
                    JOptionPane.showMessageDialog(this, "Mã lớp đã tồn tại", "Đã xảy ra lỗi", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (txtTenLop.getText().trim().isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Vui lòng điền tên lớp", "Đã xảy ra lỗi", JOptionPane.ERROR_MESSAGE);
                    } else {
                        String tenLop = txtTenLop.getText();
                        Lop lop = new Lop(malop, tenLop);
                        lopServices.addLop(lop);
                        defaultTableModel.setRowCount(0);
                        fillData(lopServices.getLop());
                    }
                }
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnReLoad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelMaLop;
    private javax.swing.JLabel labelTenLop;
    private javax.swing.JLabel labelTitile;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtMaLop;
    private javax.swing.JEditorPane txtTenLop;
    // End of variables declaration//GEN-END:variables
}
