/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vannguyen.Views;

import com.vannguyen.Dao.DetailTrangDao;
import com.vannguyen.Dao.NewDao;
import com.vannguyen.Model.DetailTrang;
import com.vannguyen.Services.DetailTrangServices;
import com.vannguyen.Services.GiaovienServices;
import com.vannguyen.Services.MonhocServices;
import com.vannguyen.Services.SoLLServices;
import com.vannguyen.Services.TrangServices;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen
 */
public class SinhvienMain extends javax.swing.JFrame {

    /**
     * Creates new form Sinhvien
     */
    DefaultTableModel defaultTableModel;
    DetailTrangServices detailTrangServices;
    GiaovienServices giaovienServices;
    TrangServices trangServices;
    MonhocServices monhocServices;
    SoLLServices soLLServices;
    String maTrang = "";
    String maGV = "";
    String tenMH = "";
    String maMH = "";
    String namHoc = "";
    String buoi = "";
    String ngayLL = "";
    String maSV = "";

    public SinhvienMain(String maSV) {
        initComponents();
        this.maSV = maSV;
        System.out.println("ma sinh vien = " + maSV);
        enableDetail(false);
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        detailTrangServices = new DetailTrangServices();
        giaovienServices = new GiaovienServices();
        trangServices = new TrangServices();
        monhocServices = new MonhocServices();
        soLLServices = new SoLLServices();
        table.setModel(defaultTableModel);
        table.setAutoCreateRowSorter(true);
        defaultTableModel.addColumn("Ngày lên lớp");
        defaultTableModel.addColumn("Buổi");
        defaultTableModel.addColumn("Phòng");
        defaultTableModel.addColumn("Số tiết lý thuyết");
        defaultTableModel.addColumn("Số tiết thực hành");
        defaultTableModel.addColumn("Tóm tắt nội dung");
        defaultTableModel.addColumn("Sinh viên vắng");
        defaultTableModel.addColumn("Sinh viên ký tên");
        loadTenMH();
        loadMaGV();
        loadNamHoc();
        txtTenGV.setText("");
        txtTenDV.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void loadMaGV() {
        ArrayList<String> list = NewDao.loadMaGVtoCombo();
        for (String item : list) {
            comboMaGV.addItem(item);
        }
    }

    private void loadNamHoc() {
        ArrayList<String> list = NewDao.loadNamhocToCombo();
        for (String item : list) {
            comboNamHoc.addItem(item);
        }
    }

    private void FillData(List<DetailTrang> list) {
        defaultTableModel.setRowCount(0);
        for (DetailTrang detailTrang : list) {
            defaultTableModel.addRow(new Object[]{
                detailTrang.getNgayLL(),
                detailTrang.getBuoi(),
                detailTrang.getPhong(),
                detailTrang.getLyThuyet(),
                detailTrang.getThucHanh(),
                detailTrang.getTomTat(),
                detailTrang.getSinhvienVang(),
                detailTrang.getMaSV()
            });
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNgayLL = new javax.swing.JTextField();
        txtBuoi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTomTat = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSinhvienVang = new javax.swing.JEditorPane();
        btnKyTen = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        comboTenMon = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboNamHoc = new javax.swing.JComboBox<>();
        comboMaGV = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnLogOut = new javax.swing.JButton();
        txtTenGV = new javax.swing.JLabel();
        txtTenDV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Sổ lên lớp điện tử");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Ngày lên lớp");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Buổi");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Tóm tắt nội dung");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Sinh viên vắng");

        txtNgayLL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNgayLL.setEnabled(false);

        txtBuoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBuoi.setEnabled(false);

        txtTomTat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTomTat.setEnabled(false);
        jScrollPane1.setViewportView(txtTomTat);

        txtSinhvienVang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSinhvienVang.setEnabled(false);
        jScrollPane2.setViewportView(txtSinhvienVang);

        btnKyTen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnKyTen.setText("Ký tên");
        btnKyTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKyTenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBuoi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayLL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel10))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKyTen)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayLL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKyTen)
                .addGap(39, 39, 39))
        );

        jScrollPane3.setViewportView(jPanel1);

        btnSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSearch.setText("Tìm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        comboTenMon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Tên môn học");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Năm học");

        comboNamHoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        comboMaGV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Mã giáo viên");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(table);

        btnLogOut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLogOut.setText("Đăng xuất");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        txtTenGV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTenGV.setText("jLabel4");

        txtTenDV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTenDV.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(comboMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(comboNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSearch)
                                    .addComponent(comboTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtTenGV)
                                .addGap(252, 252, 252)
                                .addComponent(txtTenDV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogOut)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLogOut)
                        .addComponent(txtTenGV)
                        .addComponent(txtTenDV)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(comboTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6))
                .addGap(99, 99, 99))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadTenMH() {
        ArrayList<String> list = NewDao.loadMonhocToCombo();
        for (String item : list) {
            comboTenMon.addItem(item);
        }
    }

    private void enableDetail(boolean check) {
        btnKyTen.setEnabled(check);
    }

    private void ShowError(String error) {
        JOptionPane.showMessageDialog(this, error, "Đã xảy ra lỗi", JOptionPane.ERROR_MESSAGE);
    }

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        tenMH = comboTenMon.getSelectedItem().toString();
        maMH = NewDao.getMaMH(tenMH);
        maGV = comboMaGV.getSelectedItem().toString();
        namHoc = comboNamHoc.getSelectedItem().toString();
        maTrang = NewDao.getMaTrang(maGV, namHoc, maSV, maMH);
        enableDetail(true);
        FillData(detailTrangServices.getDetail(maTrang));
        System.out.println("maTrang = " + maTrang);
        txtTenGV.setText("Tên giáo viên: " + NewDao.getTenGV(maGV));
        txtTenDV.setText("Tên đơn vị: " + NewDao.getTenDV(maGV));
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnKyTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKyTenActionPerformed
        // TODO add your handling code here:
        if (!txtNgayLL.getText().trim().isEmpty()) {
            if (NewDao.checkLopSV(maTrang, maSV)) {
                if (NewDao.checkKyten(maTrang, ngayLL, buoi)) {
                    NewDao.kyTen(maTrang, maSV, ngayLL, buoi);
                    FillData(detailTrangServices.getDetail(maTrang));
                } else {
                    ShowError("Buổi học đã có sinh viên đại diện");
                }
            } else {
                ShowError("Sinh viên không thuộc lớp này");
            }
        }
    }//GEN-LAST:event_btnKyTenActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        txtNgayLL.setText(table.getValueAt(row, 0).toString());
        txtBuoi.setText(table.getValueAt(row, 1).toString());
        txtTomTat.setText(table.getValueAt(row, 5).toString());
        txtSinhvienVang.setText(table.getValueAt(row, 6).toString());
        ngayLL = txtNgayLL.getText().trim();
        buoi = txtBuoi.getText().trim();

    }//GEN-LAST:event_tableMouseClicked

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SinhvienMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SinhvienMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SinhvienMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SinhvienMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SinhvienMain().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKyTen;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboMaGV;
    private javax.swing.JComboBox<String> comboNamHoc;
    private javax.swing.JComboBox<String> comboTenMon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtBuoi;
    private javax.swing.JTextField txtNgayLL;
    private javax.swing.JEditorPane txtSinhvienVang;
    private javax.swing.JLabel txtTenDV;
    private javax.swing.JLabel txtTenGV;
    private javax.swing.JEditorPane txtTomTat;
    // End of variables declaration//GEN-END:variables
}
